collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6039426
  brandStrength: 0.7485065
  rhythmicContrast: 0
  brandColors:
    - '#FE0103'
    - '#251812'
    - '#FDFBEF'
    - '#984116'
    - '#CEC2B4'
  lightness: 1
typography_spectrum: 0.1069295
layout_spectrum: 1
name: 'Papa Smurf DC '
